little rewrite and can now handle 3 different svtplay-types

diff --git a/bash/svtget b/bash/svtget
--- a/bash/svtget
+++ b/bash/svtget
@@ -23,7 +23,7 @@
 # Sample usage:
 # ./svtget http://svtplay.se/v/2440756/k_special/presspauseplay
 
-DEPENDENCIES="rtmpdump curl sed cut bash"
+DEPENDENCIES="rtmpdump curl sed cut bash vlc wget"
 for DEP in $DEPENDENCIES; do
 	if [ -z "`which $DEP`" ]; then
 		echo "ERROR: Missing dependency '$DEP'." >&2
@@ -54,21 +54,23 @@ function get_tcUrls {
 	if [ $? -gt 0 ] || [ -z "$bitrate" ] || [ "$bitrate" -eq 0 ]; then
 		bitrate='[0-9]\+'
 	fi
-	echo $html | sed "s/\(rtmp[e]\?:[^|&]*\),bitrate:\($bitrate\)/\\n\2|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq 
-}
-
-function get_tcUrls_oa {
-	local html=$1
-	echo $html | sed "s/\(rtmp[e]\?:[^|&]*\)&amp;/\\n320|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq 
+  #normal clip
+	tcUrls=`echo $html | sed "s/\(rtmp[e]\?:[^|&]*\),bitrate:\($bitrate\)/\\n\2|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq` 
+	if [ -z "$tcUrls" ]; then
+    #from öppet arkiv
+	  tcUrls=`echo $html | sed "s/\(rtmp[e]\?:[^|&]*\)&amp;/\\n320|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq` 
+  fi
+  if [ -z "$tcUrls" ]; then
+    #flv-files
+	  tcUrls=`echo $html | sed "s/\(http\?:[^|&]*\.flv\)&amp;/\\n320|\1\\n/g" | grep -E '^[[:digit:]]+\|' | sort -n | uniq` 
+  fi
+  echo $tcUrls
 }
 
 function get_sub {
 	local html=$1
-	echo -ne "\nwant subtitle? [y/n] "
-	read ask_sub
-	if [ -n "$ask_sub" ] && [ "y" == "$ask_sub" ]; then
-		subUrl=`echo $html | sed "s/subtitle\=\(http:[^|&]*\)\&amp/\\n\-\-sub\-file \1\\n/g"| grep "\-\-sub\-file " | uniq` 
-	fi
+	subUrl=`echo $html | sed "s/subtitle\=\(http:[^|&]*\)\&amp/\\n\-\-sub\-file \1\\n/g"| grep "\-\-sub\-file " | uniq` 
+  echo $subUrl
 }
 
 function pick_tcUrl {
@@ -123,20 +125,17 @@ HTML=`curl -s "$pageUrl"`
 swfUrl="http://svtplay.se$(echo $HTML | sed 's/.*x-shockwave-flash" data="\([^"]\+\)\".*/\1/')"
 tcUrls=$(get_tcUrls "$HTML" "$BITRATE")
 if [ -z "$tcUrls" ]; then
-tcUrls=$(get_tcUrls_oa "$HTML" )
-	get_tcUrls_oa "$HTML"
-	if [ -z "$tcUrls" ]; then
-		echo "ERROR: No rtmp streams found. No clip in that quality?
+	echo "ERROR: No rtmp streams found. No clip in that quality?
 Please visit http://svtget.se/ for updates and information. If the website's down, use a search engine to find copies." >&2
-		exit 1
-	fi
+	exit 1
 fi
 
 pick_tcUrl $tcUrls
 
-extension="mp4"
-if [ "$extension" != "${tcUrl##*.}" ]; then
+if [ "${tcUrl##*.}" == "flv" ]; then
 	extension="flv"
+else
+  extension="mp4"
 fi
 filename="$(basename $pageUrl).$extension"
 prefix="$(basename $(dirname $pageUrl))"
@@ -144,19 +143,52 @@ if echo "$prefix" | grep -qE '[^0-9]+' ; then
   filename="${prefix}_${filename}"
 fi
 
-get_sub "$HTML"
+
+echo -ne "\nwant subtitle? [y/n] "
+read ask_sub
+if [ -n "$ask_sub" ] && [ "y" == "$ask_sub" ]; then
+  subUrl=$(get_sub "$HTML")
+  subtitle=true
+	sub_filename="$(basename $pageUrl).srt"
+else
+  subUrl=""
+  subtitle=false
+fi
 
 echo -ne "\nDo you want to view i vlc or save to file? [v/f] "
 read ask_vlc
 if [ -n "$ask_vlc" ] && [ "v" == "$ask_vlc" ]; then
-	rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o - | vlc - $subUrl
+  method="vlc"
 elif [ -n "$ask_vlc" ] && [ "f" == "$ask_vlc" ]; then
-	echo Running RTMPDump for "$tcUrl" and saving to "$filename"
-	#rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o "$filename"
-	if [ -n "$subUrl" ]; then
-		subUrl=`echo "$subUrl" | sed 's/\-\-sub\-file //g'`
-		sub_filename="$(basename $pageUrl).srt"
-		echo " and subtitle to: "$sub_filename
-		wget $subUrl -O $sub_filename
-	fi
+  method="file"
+fi
+
+if [ $method == "file" ]; then
+  echo "file"
+  if [ $extension == "mp4" ]; then
+    echo "mp4"
+    echo "rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o "$filename""
+    rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o "$filename"
+  elif [ $extension == "flv" ]; then
+    echo "flv"
+    echo "wget "$tcUrl" -O "$filename""
+    wget "$tcUrl" -O "$filename"
+  fi
+  if [ $subtitle == true ]; then
+    echo "subtitle"
+	  subUrl=`echo "$subUrl" | sed 's/\-\-sub\-file //g'`
+	  echo "wget "$subUrl" -O "$sub_filename""
+	  wget "$subUrl" -O "$sub_filename"
+  fi
+elif [ $method == "vlc" ]; then
+  echo "vlc"
+  if [ $extension == "mp4" ]; then
+    echo "mp4"
+	  echo "rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o - | vlc - $subUrl"
+	  rtmpdump -r "$tcUrl" --swfVfy="$swfUrl" -o - | vlc - $subUrl
+  elif [ $extension == "flv" ]; then
+    echo "flv"
+    echo "vlc "$tcUrl" "$subUrl""
+    vlc "$tcUrl" "$subUrl"
+  fi
 fi
